/* Automatically @generated by tree-sitter */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 15
#define STATE_COUNT 16
#define LARGE_STATE_COUNT 2
#define SYMBOL_COUNT 15
#define ALIAS_COUNT 0
#define TOKEN_COUNT 9
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 1
#define MAX_ALIAS_SEQUENCE_LENGTH 4
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 4
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  anon_sym_ATimport = 1,
  anon_sym_LPAREN = 2,
  anon_sym_RPAREN = 3,
  anon_sym_using = 4,
  anon_sym_SEMI = 5,
  anon_sym_EQ = 6,
  sym_string_literal = 7,
  sym_identifier = 8,
  sym_source_file = 9,
  sym__imports = 10,
  sym__generic_import = 11,
  sym_global_import = 12,
  sym_alias_import = 13,
  aux_sym_source_file_repeat1 = 14,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [anon_sym_ATimport] = "@import",
  [anon_sym_LPAREN] = "(",
  [anon_sym_RPAREN] = ")",
  [anon_sym_using] = "using",
  [anon_sym_SEMI] = ";",
  [anon_sym_EQ] = "=",
  [sym_string_literal] = "string_literal",
  [sym_identifier] = "identifier",
  [sym_source_file] = "source_file",
  [sym__imports] = "_imports",
  [sym__generic_import] = "_generic_import",
  [sym_global_import] = "global_import",
  [sym_alias_import] = "alias_import",
  [aux_sym_source_file_repeat1] = "source_file_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [anon_sym_ATimport] = anon_sym_ATimport,
  [anon_sym_LPAREN] = anon_sym_LPAREN,
  [anon_sym_RPAREN] = anon_sym_RPAREN,
  [anon_sym_using] = anon_sym_using,
  [anon_sym_SEMI] = anon_sym_SEMI,
  [anon_sym_EQ] = anon_sym_EQ,
  [sym_string_literal] = sym_string_literal,
  [sym_identifier] = sym_identifier,
  [sym_source_file] = sym_source_file,
  [sym__imports] = sym__imports,
  [sym__generic_import] = sym__generic_import,
  [sym_global_import] = sym_global_import,
  [sym_alias_import] = sym_alias_import,
  [aux_sym_source_file_repeat1] = aux_sym_source_file_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_ATimport] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_using] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_SEMI] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_EQ] = {
    .visible = true,
    .named = false,
  },
  [sym_string_literal] = {
    .visible = true,
    .named = true,
  },
  [sym_identifier] = {
    .visible = true,
    .named = true,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym__imports] = {
    .visible = false,
    .named = true,
  },
  [sym__generic_import] = {
    .visible = false,
    .named = true,
  },
  [sym_global_import] = {
    .visible = true,
    .named = true,
  },
  [sym_alias_import] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_source_file_repeat1] = {
    .visible = false,
    .named = false,
  },
};

enum ts_field_identifiers {
  field_path = 1,
};

static const char * const ts_field_names[] = {
  [0] = NULL,
  [field_path] = "path",
};

static const TSMapSlice ts_field_map_slices[PRODUCTION_ID_COUNT] = {
  [1] = {.index = 0, .length = 1},
  [2] = {.index = 1, .length = 1},
  [3] = {.index = 2, .length = 1},
};

static const TSFieldMapEntry ts_field_map_entries[] = {
  [0] =
    {field_path, 1, .inherited = true},
  [1] =
    {field_path, 2, .inherited = true},
  [2] =
    {field_path, 2},
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(57);
      if (lookahead == '"') ADVANCE(30);
      if (lookahead == '(') ADVANCE(63);
      if (lookahead == ')') ADVANCE(68);
      if (lookahead == '/') SKIP(54);
      if (lookahead == ';') ADVANCE(78);
      if (lookahead == '=') ADVANCE(83);
      if (lookahead == '@') ADVANCE(45);
      if (lookahead == 'u') ADVANCE(123);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(0);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(126);
      END_STATE();
    case 1:
      ADVANCE_MAP(
        '\n', 31,
        '"', 89,
        '(', 64,
        ')', 69,
        '/', 2,
        ';', 79,
        '=', 84,
        '@', 1,
        '\\', 5,
        'i', 94,
        'u', 99,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(2);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(101);
      if (lookahead != 0) ADVANCE(2);
      END_STATE();
    case 2:
      ADVANCE_MAP(
        '\n', 31,
        '"', 89,
        '(', 64,
        ')', 69,
        '/', 2,
        ';', 79,
        '=', 84,
        '@', 1,
        '\\', 5,
        'u', 99,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(2);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(101);
      if (lookahead != 0) ADVANCE(2);
      END_STATE();
    case 3:
      if (lookahead == '\n') SKIP(20);
      if (lookahead == '"') ADVANCE(2);
      if (lookahead == '(') ADVANCE(66);
      if (lookahead == ')') ADVANCE(71);
      if (lookahead == '/') SKIP(4);
      if (lookahead == ';') ADVANCE(81);
      if (lookahead == '=') ADVANCE(86);
      if (lookahead == '@') ADVANCE(3);
      if (lookahead == 'i') ADVANCE(109);
      if (lookahead == 'u') ADVANCE(114);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(4);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(116);
      if (lookahead != 0) SKIP(4);
      END_STATE();
    case 4:
      if (lookahead == '\n') SKIP(20);
      if (lookahead == '"') ADVANCE(2);
      if (lookahead == '(') ADVANCE(66);
      if (lookahead == ')') ADVANCE(71);
      if (lookahead == '/') SKIP(4);
      if (lookahead == ';') ADVANCE(81);
      if (lookahead == '=') ADVANCE(86);
      if (lookahead == '@') ADVANCE(3);
      if (lookahead == 'u') ADVANCE(114);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(4);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(116);
      if (lookahead != 0) SKIP(4);
      END_STATE();
    case 5:
      if (lookahead == '\n') SKIP(20);
      if (lookahead == '"') ADVANCE(2);
      if (lookahead == '(') ADVANCE(64);
      if (lookahead == ')') ADVANCE(69);
      if (lookahead == '/') ADVANCE(2);
      if (lookahead == ';') ADVANCE(79);
      if (lookahead == '=') ADVANCE(84);
      if (lookahead == '@') ADVANCE(1);
      if (lookahead == 'u') ADVANCE(99);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(2);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(101);
      if (lookahead != 0) ADVANCE(2);
      END_STATE();
    case 6:
      if (lookahead == '\n') SKIP(42);
      if (lookahead == '/') SKIP(12);
      if (lookahead == '@') ADVANCE(6);
      if (lookahead == 'i') ADVANCE(7);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(12);
      if (lookahead != 0) SKIP(12);
      END_STATE();
    case 7:
      if (lookahead == '\n') SKIP(42);
      if (lookahead == '/') SKIP(12);
      if (lookahead == '@') ADVANCE(6);
      if (lookahead == 'm') ADVANCE(9);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(12);
      if (lookahead != 0) SKIP(12);
      END_STATE();
    case 8:
      if (lookahead == '\n') SKIP(42);
      if (lookahead == '/') SKIP(12);
      if (lookahead == '@') ADVANCE(6);
      if (lookahead == 'o') ADVANCE(10);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(12);
      if (lookahead != 0) SKIP(12);
      END_STATE();
    case 9:
      if (lookahead == '\n') SKIP(42);
      if (lookahead == '/') SKIP(12);
      if (lookahead == '@') ADVANCE(6);
      if (lookahead == 'p') ADVANCE(8);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(12);
      if (lookahead != 0) SKIP(12);
      END_STATE();
    case 10:
      if (lookahead == '\n') SKIP(42);
      if (lookahead == '/') SKIP(12);
      if (lookahead == '@') ADVANCE(6);
      if (lookahead == 'r') ADVANCE(11);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(12);
      if (lookahead != 0) SKIP(12);
      END_STATE();
    case 11:
      if (lookahead == '\n') SKIP(42);
      if (lookahead == '/') SKIP(12);
      if (lookahead == '@') ADVANCE(6);
      if (lookahead == 't') ADVANCE(62);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(12);
      if (lookahead != 0) SKIP(12);
      END_STATE();
    case 12:
      if (lookahead == '\n') SKIP(42);
      if (lookahead == '/') SKIP(12);
      if (lookahead == '@') ADVANCE(6);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(12);
      if (lookahead != 0) SKIP(12);
      END_STATE();
    case 13:
      if (lookahead == '\n') SKIP(43);
      if (lookahead == '/') SKIP(13);
      if (lookahead == '=') ADVANCE(87);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(13);
      if (lookahead != 0) SKIP(13);
      END_STATE();
    case 14:
      if (lookahead == '\n') SKIP(33);
      if (lookahead == '(') ADVANCE(67);
      if (lookahead == '/') SKIP(14);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(14);
      if (lookahead != 0) SKIP(14);
      END_STATE();
    case 15:
      if (lookahead == '\n') SKIP(44);
      if (lookahead == '/') SKIP(15);
      if (lookahead == ';') ADVANCE(82);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(15);
      if (lookahead != 0) SKIP(15);
      END_STATE();
    case 16:
      if (lookahead == '\n') SKIP(21);
      if (lookahead == '"') ADVANCE(18);
      if (lookahead == '/') SKIP(16);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(16);
      if (lookahead != 0) SKIP(16);
      END_STATE();
    case 17:
      if (lookahead == '\n') SKIP(21);
      if (lookahead == '"') ADVANCE(18);
      if (lookahead == '/') ADVANCE(18);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(18);
      if (lookahead != 0) ADVANCE(18);
      END_STATE();
    case 18:
      if (lookahead == '\n') ADVANCE(32);
      if (lookahead == '"') ADVANCE(90);
      if (lookahead == '/') ADVANCE(18);
      if (lookahead == '\\') ADVANCE(17);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(18);
      if (lookahead != 0) ADVANCE(18);
      END_STATE();
    case 19:
      if (lookahead == '\n') SKIP(34);
      if (lookahead == ')') ADVANCE(72);
      if (lookahead == '/') SKIP(19);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(19);
      if (lookahead != 0) SKIP(19);
      END_STATE();
    case 20:
      if (lookahead == '"') ADVANCE(30);
      if (lookahead == '(') ADVANCE(63);
      if (lookahead == ')') ADVANCE(68);
      if (lookahead == '/') SKIP(35);
      if (lookahead == ';') ADVANCE(78);
      if (lookahead == '=') ADVANCE(83);
      if (lookahead == '@') ADVANCE(45);
      if (lookahead == 'u') ADVANCE(123);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(20);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(126);
      END_STATE();
    case 21:
      if (lookahead == '"') ADVANCE(30);
      if (lookahead == '/') SKIP(40);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(21);
      END_STATE();
    case 22:
      if (lookahead == '"') ADVANCE(88);
      if (lookahead == '/') ADVANCE(2);
      if (lookahead == '\\') ADVANCE(51);
      if (lookahead != 0) ADVANCE(30);
      END_STATE();
    case 23:
      if (lookahead == '"') ADVANCE(88);
      if (lookahead == '/') ADVANCE(18);
      if (lookahead == '\\') ADVANCE(51);
      if (lookahead != 0) ADVANCE(30);
      END_STATE();
    case 24:
      if (lookahead == '"') ADVANCE(88);
      if (lookahead == '\\') ADVANCE(51);
      if (lookahead == 'i') ADVANCE(25);
      if (lookahead != 0) ADVANCE(30);
      END_STATE();
    case 25:
      if (lookahead == '"') ADVANCE(88);
      if (lookahead == '\\') ADVANCE(51);
      if (lookahead == 'm') ADVANCE(27);
      if (lookahead != 0) ADVANCE(30);
      END_STATE();
    case 26:
      if (lookahead == '"') ADVANCE(88);
      if (lookahead == '\\') ADVANCE(51);
      if (lookahead == 'o') ADVANCE(28);
      if (lookahead != 0) ADVANCE(30);
      END_STATE();
    case 27:
      if (lookahead == '"') ADVANCE(88);
      if (lookahead == '\\') ADVANCE(51);
      if (lookahead == 'p') ADVANCE(26);
      if (lookahead != 0) ADVANCE(30);
      END_STATE();
    case 28:
      if (lookahead == '"') ADVANCE(88);
      if (lookahead == '\\') ADVANCE(51);
      if (lookahead == 'r') ADVANCE(29);
      if (lookahead != 0) ADVANCE(30);
      END_STATE();
    case 29:
      if (lookahead == '"') ADVANCE(88);
      if (lookahead == '\\') ADVANCE(51);
      if (lookahead == 't') ADVANCE(60);
      if (lookahead != 0) ADVANCE(30);
      END_STATE();
    case 30:
      if (lookahead == '"') ADVANCE(88);
      if (lookahead == '\\') ADVANCE(51);
      if (lookahead != 0) ADVANCE(30);
      END_STATE();
    case 31:
      ADVANCE_MAP(
        '"', 91,
        '(', 65,
        ')', 70,
        '/', 22,
        ';', 80,
        '=', 85,
        '@', 24,
        '\\', 51,
        'u', 105,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(31);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(106);
      if (lookahead != 0) ADVANCE(30);
      END_STATE();
    case 32:
      if (lookahead == '"') ADVANCE(91);
      if (lookahead == '/') ADVANCE(23);
      if (lookahead == '\\') ADVANCE(51);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(32);
      if (lookahead != 0) ADVANCE(30);
      END_STATE();
    case 33:
      if (lookahead == '(') ADVANCE(63);
      if (lookahead == '/') SKIP(38);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(33);
      END_STATE();
    case 34:
      if (lookahead == ')') ADVANCE(68);
      if (lookahead == '/') SKIP(41);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(34);
      END_STATE();
    case 35:
      if (lookahead == '/') SKIP(4);
      END_STATE();
    case 36:
      if (lookahead == '/') SKIP(12);
      END_STATE();
    case 37:
      if (lookahead == '/') SKIP(13);
      END_STATE();
    case 38:
      if (lookahead == '/') SKIP(14);
      END_STATE();
    case 39:
      if (lookahead == '/') SKIP(15);
      END_STATE();
    case 40:
      if (lookahead == '/') SKIP(16);
      END_STATE();
    case 41:
      if (lookahead == '/') SKIP(19);
      END_STATE();
    case 42:
      if (lookahead == '/') SKIP(36);
      if (lookahead == '@') ADVANCE(45);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(42);
      END_STATE();
    case 43:
      if (lookahead == '/') SKIP(37);
      if (lookahead == '=') ADVANCE(83);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(43);
      END_STATE();
    case 44:
      if (lookahead == '/') SKIP(39);
      if (lookahead == ';') ADVANCE(78);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(44);
      END_STATE();
    case 45:
      if (lookahead == 'i') ADVANCE(46);
      END_STATE();
    case 46:
      if (lookahead == 'm') ADVANCE(48);
      END_STATE();
    case 47:
      if (lookahead == 'o') ADVANCE(49);
      END_STATE();
    case 48:
      if (lookahead == 'p') ADVANCE(47);
      END_STATE();
    case 49:
      if (lookahead == 'r') ADVANCE(50);
      END_STATE();
    case 50:
      if (lookahead == 't') ADVANCE(58);
      END_STATE();
    case 51:
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(30);
      END_STATE();
    case 52:
      if (eof) ADVANCE(57);
      if (lookahead == '\n') SKIP(0);
      if (lookahead == '"') ADVANCE(2);
      if (lookahead == '(') ADVANCE(66);
      if (lookahead == ')') ADVANCE(71);
      if (lookahead == '/') SKIP(52);
      if (lookahead == ';') ADVANCE(81);
      if (lookahead == '=') ADVANCE(86);
      if (lookahead == '@') ADVANCE(3);
      if (lookahead == 'u') ADVANCE(114);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(52);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(116);
      if (lookahead != 0) SKIP(52);
      END_STATE();
    case 53:
      if (eof) ADVANCE(57);
      if (lookahead == '\n') SKIP(56);
      if (lookahead == '/') SKIP(53);
      if (lookahead == 'u') ADVANCE(124);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(53);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(125);
      if (lookahead != 0) SKIP(53);
      END_STATE();
    case 54:
      if (eof) ADVANCE(57);
      if (lookahead == '/') SKIP(52);
      END_STATE();
    case 55:
      if (eof) ADVANCE(57);
      if (lookahead == '/') SKIP(53);
      END_STATE();
    case 56:
      if (eof) ADVANCE(57);
      if (lookahead == '/') SKIP(55);
      if (lookahead == 'u') ADVANCE(123);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(56);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(126);
      END_STATE();
    case 57:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 58:
      ACCEPT_TOKEN(anon_sym_ATimport);
      END_STATE();
    case 59:
      ACCEPT_TOKEN(anon_sym_ATimport);
      ADVANCE_MAP(
        '\n', 31,
        '"', 89,
        '(', 64,
        ')', 69,
        '/', 2,
        ';', 79,
        '=', 84,
        '@', 1,
        '\\', 5,
        'u', 99,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(2);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(101);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(101);
      if (lookahead != 0) ADVANCE(2);
      END_STATE();
    case 60:
      ACCEPT_TOKEN(anon_sym_ATimport);
      if (lookahead == '"') ADVANCE(88);
      if (lookahead == '\\') ADVANCE(51);
      if (lookahead != 0) ADVANCE(30);
      END_STATE();
    case 61:
      ACCEPT_TOKEN(anon_sym_ATimport);
      if (lookahead == '"') ADVANCE(2);
      if (lookahead == '(') ADVANCE(66);
      if (lookahead == ')') ADVANCE(71);
      if (lookahead == ';') ADVANCE(81);
      if (lookahead == '=') ADVANCE(86);
      if (lookahead == '@') ADVANCE(3);
      if (lookahead == 'u') ADVANCE(114);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(116);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(116);
      END_STATE();
    case 62:
      ACCEPT_TOKEN(anon_sym_ATimport);
      if (lookahead == '@') ADVANCE(6);
      END_STATE();
    case 63:
      ACCEPT_TOKEN(anon_sym_LPAREN);
      END_STATE();
    case 64:
      ACCEPT_TOKEN(anon_sym_LPAREN);
      ADVANCE_MAP(
        '\n', 31,
        '"', 89,
        '(', 64,
        ')', 69,
        '/', 2,
        ';', 79,
        '=', 84,
        '@', 1,
        '\\', 5,
        'u', 99,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(2);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(101);
      if (lookahead != 0) ADVANCE(2);
      END_STATE();
    case 65:
      ACCEPT_TOKEN(anon_sym_LPAREN);
      if (lookahead == '"') ADVANCE(88);
      if (lookahead == '\\') ADVANCE(51);
      if (lookahead != 0) ADVANCE(30);
      END_STATE();
    case 66:
      ACCEPT_TOKEN(anon_sym_LPAREN);
      if (lookahead == '"') ADVANCE(2);
      if (lookahead == '(') ADVANCE(66);
      if (lookahead == ')') ADVANCE(71);
      if (lookahead == ';') ADVANCE(81);
      if (lookahead == '=') ADVANCE(86);
      if (lookahead == '@') ADVANCE(3);
      if (lookahead == 'u') ADVANCE(114);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(116);
      END_STATE();
    case 67:
      ACCEPT_TOKEN(anon_sym_LPAREN);
      if (lookahead == '(') ADVANCE(67);
      END_STATE();
    case 68:
      ACCEPT_TOKEN(anon_sym_RPAREN);
      END_STATE();
    case 69:
      ACCEPT_TOKEN(anon_sym_RPAREN);
      ADVANCE_MAP(
        '\n', 31,
        '"', 89,
        '(', 64,
        ')', 69,
        '/', 2,
        ';', 79,
        '=', 84,
        '@', 1,
        '\\', 5,
        'u', 99,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(2);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(101);
      if (lookahead != 0) ADVANCE(2);
      END_STATE();
    case 70:
      ACCEPT_TOKEN(anon_sym_RPAREN);
      if (lookahead == '"') ADVANCE(88);
      if (lookahead == '\\') ADVANCE(51);
      if (lookahead != 0) ADVANCE(30);
      END_STATE();
    case 71:
      ACCEPT_TOKEN(anon_sym_RPAREN);
      if (lookahead == '"') ADVANCE(2);
      if (lookahead == '(') ADVANCE(66);
      if (lookahead == ')') ADVANCE(71);
      if (lookahead == ';') ADVANCE(81);
      if (lookahead == '=') ADVANCE(86);
      if (lookahead == '@') ADVANCE(3);
      if (lookahead == 'u') ADVANCE(114);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(116);
      END_STATE();
    case 72:
      ACCEPT_TOKEN(anon_sym_RPAREN);
      if (lookahead == ')') ADVANCE(72);
      END_STATE();
    case 73:
      ACCEPT_TOKEN(anon_sym_using);
      ADVANCE_MAP(
        '\n', 31,
        '"', 89,
        '(', 64,
        ')', 69,
        '/', 2,
        ';', 79,
        '=', 84,
        '@', 1,
        '\\', 5,
        'u', 99,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(2);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(101);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(101);
      if (lookahead != 0) ADVANCE(2);
      END_STATE();
    case 74:
      ACCEPT_TOKEN(anon_sym_using);
      if (lookahead == '"') ADVANCE(88);
      if (lookahead == '\\') ADVANCE(51);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(106);
      if (lookahead != 0) ADVANCE(30);
      END_STATE();
    case 75:
      ACCEPT_TOKEN(anon_sym_using);
      if (lookahead == '"') ADVANCE(2);
      if (lookahead == '(') ADVANCE(66);
      if (lookahead == ')') ADVANCE(71);
      if (lookahead == ';') ADVANCE(81);
      if (lookahead == '=') ADVANCE(86);
      if (lookahead == '@') ADVANCE(3);
      if (lookahead == 'u') ADVANCE(114);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(116);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(116);
      END_STATE();
    case 76:
      ACCEPT_TOKEN(anon_sym_using);
      if (lookahead == 'u') ADVANCE(124);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(125);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(125);
      END_STATE();
    case 77:
      ACCEPT_TOKEN(anon_sym_using);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(126);
      END_STATE();
    case 78:
      ACCEPT_TOKEN(anon_sym_SEMI);
      END_STATE();
    case 79:
      ACCEPT_TOKEN(anon_sym_SEMI);
      ADVANCE_MAP(
        '\n', 31,
        '"', 89,
        '(', 64,
        ')', 69,
        '/', 2,
        ';', 79,
        '=', 84,
        '@', 1,
        '\\', 5,
        'u', 99,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(2);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(101);
      if (lookahead != 0) ADVANCE(2);
      END_STATE();
    case 80:
      ACCEPT_TOKEN(anon_sym_SEMI);
      if (lookahead == '"') ADVANCE(88);
      if (lookahead == '\\') ADVANCE(51);
      if (lookahead != 0) ADVANCE(30);
      END_STATE();
    case 81:
      ACCEPT_TOKEN(anon_sym_SEMI);
      if (lookahead == '"') ADVANCE(2);
      if (lookahead == '(') ADVANCE(66);
      if (lookahead == ')') ADVANCE(71);
      if (lookahead == ';') ADVANCE(81);
      if (lookahead == '=') ADVANCE(86);
      if (lookahead == '@') ADVANCE(3);
      if (lookahead == 'u') ADVANCE(114);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(116);
      END_STATE();
    case 82:
      ACCEPT_TOKEN(anon_sym_SEMI);
      if (lookahead == ';') ADVANCE(82);
      END_STATE();
    case 83:
      ACCEPT_TOKEN(anon_sym_EQ);
      END_STATE();
    case 84:
      ACCEPT_TOKEN(anon_sym_EQ);
      ADVANCE_MAP(
        '\n', 31,
        '"', 89,
        '(', 64,
        ')', 69,
        '/', 2,
        ';', 79,
        '=', 84,
        '@', 1,
        '\\', 5,
        'u', 99,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(2);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(101);
      if (lookahead != 0) ADVANCE(2);
      END_STATE();
    case 85:
      ACCEPT_TOKEN(anon_sym_EQ);
      if (lookahead == '"') ADVANCE(88);
      if (lookahead == '\\') ADVANCE(51);
      if (lookahead != 0) ADVANCE(30);
      END_STATE();
    case 86:
      ACCEPT_TOKEN(anon_sym_EQ);
      if (lookahead == '"') ADVANCE(2);
      if (lookahead == '(') ADVANCE(66);
      if (lookahead == ')') ADVANCE(71);
      if (lookahead == ';') ADVANCE(81);
      if (lookahead == '=') ADVANCE(86);
      if (lookahead == '@') ADVANCE(3);
      if (lookahead == 'u') ADVANCE(114);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(116);
      END_STATE();
    case 87:
      ACCEPT_TOKEN(anon_sym_EQ);
      if (lookahead == '=') ADVANCE(87);
      END_STATE();
    case 88:
      ACCEPT_TOKEN(sym_string_literal);
      END_STATE();
    case 89:
      ACCEPT_TOKEN(sym_string_literal);
      ADVANCE_MAP(
        '\n', 31,
        '"', 89,
        '(', 64,
        ')', 69,
        '/', 2,
        ';', 79,
        '=', 84,
        '@', 1,
        '\\', 5,
        'u', 99,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(2);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(101);
      if (lookahead != 0) ADVANCE(2);
      END_STATE();
    case 90:
      ACCEPT_TOKEN(sym_string_literal);
      if (lookahead == '\n') ADVANCE(32);
      if (lookahead == '"') ADVANCE(90);
      if (lookahead == '/') ADVANCE(18);
      if (lookahead == '\\') ADVANCE(17);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(18);
      if (lookahead != 0) ADVANCE(18);
      END_STATE();
    case 91:
      ACCEPT_TOKEN(sym_string_literal);
      if (lookahead == '"') ADVANCE(88);
      if (lookahead == '\\') ADVANCE(51);
      if (lookahead != 0) ADVANCE(30);
      END_STATE();
    case 92:
      ACCEPT_TOKEN(sym_identifier);
      ADVANCE_MAP(
        '\n', 31,
        '"', 89,
        '(', 64,
        ')', 69,
        '/', 2,
        ';', 79,
        '=', 84,
        '@', 1,
        '\\', 5,
        'g', 73,
        'u', 99,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(2);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(101);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(101);
      if (lookahead != 0) ADVANCE(2);
      END_STATE();
    case 93:
      ACCEPT_TOKEN(sym_identifier);
      ADVANCE_MAP(
        '\n', 31,
        '"', 89,
        '(', 64,
        ')', 69,
        '/', 2,
        ';', 79,
        '=', 84,
        '@', 1,
        '\\', 5,
        'i', 95,
        'u', 99,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(2);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(101);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(101);
      if (lookahead != 0) ADVANCE(2);
      END_STATE();
    case 94:
      ACCEPT_TOKEN(sym_identifier);
      ADVANCE_MAP(
        '\n', 31,
        '"', 89,
        '(', 64,
        ')', 69,
        '/', 2,
        ';', 79,
        '=', 84,
        '@', 1,
        '\\', 5,
        'm', 97,
        'u', 99,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(2);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(101);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(101);
      if (lookahead != 0) ADVANCE(2);
      END_STATE();
    case 95:
      ACCEPT_TOKEN(sym_identifier);
      ADVANCE_MAP(
        '\n', 31,
        '"', 89,
        '(', 64,
        ')', 69,
        '/', 2,
        ';', 79,
        '=', 84,
        '@', 1,
        '\\', 5,
        'n', 92,
        'u', 99,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(2);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(101);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(101);
      if (lookahead != 0) ADVANCE(2);
      END_STATE();
    case 96:
      ACCEPT_TOKEN(sym_identifier);
      ADVANCE_MAP(
        '\n', 31,
        '"', 89,
        '(', 64,
        ')', 69,
        '/', 2,
        ';', 79,
        '=', 84,
        '@', 1,
        '\\', 5,
        'o', 98,
        'u', 99,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(2);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(101);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(101);
      if (lookahead != 0) ADVANCE(2);
      END_STATE();
    case 97:
      ACCEPT_TOKEN(sym_identifier);
      ADVANCE_MAP(
        '\n', 31,
        '"', 89,
        '(', 64,
        ')', 69,
        '/', 2,
        ';', 79,
        '=', 84,
        '@', 1,
        '\\', 5,
        'p', 96,
        'u', 99,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(2);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(101);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(101);
      if (lookahead != 0) ADVANCE(2);
      END_STATE();
    case 98:
      ACCEPT_TOKEN(sym_identifier);
      ADVANCE_MAP(
        '\n', 31,
        '"', 89,
        '(', 64,
        ')', 69,
        '/', 2,
        ';', 79,
        '=', 84,
        '@', 1,
        '\\', 5,
        'r', 100,
        'u', 99,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(2);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(101);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(101);
      if (lookahead != 0) ADVANCE(2);
      END_STATE();
    case 99:
      ACCEPT_TOKEN(sym_identifier);
      ADVANCE_MAP(
        '\n', 31,
        '"', 89,
        '(', 64,
        ')', 69,
        '/', 2,
        ';', 79,
        '=', 84,
        '@', 1,
        '\\', 5,
        's', 93,
        'u', 99,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(2);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(101);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(101);
      if (lookahead != 0) ADVANCE(2);
      END_STATE();
    case 100:
      ACCEPT_TOKEN(sym_identifier);
      ADVANCE_MAP(
        '\n', 31,
        '"', 89,
        '(', 64,
        ')', 69,
        '/', 2,
        ';', 79,
        '=', 84,
        '@', 1,
        '\\', 5,
        't', 59,
        'u', 99,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(2);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(101);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(101);
      if (lookahead != 0) ADVANCE(2);
      END_STATE();
    case 101:
      ACCEPT_TOKEN(sym_identifier);
      ADVANCE_MAP(
        '\n', 31,
        '"', 89,
        '(', 64,
        ')', 69,
        '/', 2,
        ';', 79,
        '=', 84,
        '@', 1,
        '\\', 5,
        'u', 99,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(2);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(101);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(101);
      if (lookahead != 0) ADVANCE(2);
      END_STATE();
    case 102:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == '"') ADVANCE(88);
      if (lookahead == '\\') ADVANCE(51);
      if (lookahead == 'g') ADVANCE(74);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(106);
      if (lookahead != 0) ADVANCE(30);
      END_STATE();
    case 103:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == '"') ADVANCE(88);
      if (lookahead == '\\') ADVANCE(51);
      if (lookahead == 'i') ADVANCE(104);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(106);
      if (lookahead != 0) ADVANCE(30);
      END_STATE();
    case 104:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == '"') ADVANCE(88);
      if (lookahead == '\\') ADVANCE(51);
      if (lookahead == 'n') ADVANCE(102);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(106);
      if (lookahead != 0) ADVANCE(30);
      END_STATE();
    case 105:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == '"') ADVANCE(88);
      if (lookahead == '\\') ADVANCE(51);
      if (lookahead == 's') ADVANCE(103);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(106);
      if (lookahead != 0) ADVANCE(30);
      END_STATE();
    case 106:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == '"') ADVANCE(88);
      if (lookahead == '\\') ADVANCE(51);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(106);
      if (lookahead != 0) ADVANCE(30);
      END_STATE();
    case 107:
      ACCEPT_TOKEN(sym_identifier);
      ADVANCE_MAP(
        '"', 2,
        '(', 66,
        ')', 71,
        ';', 81,
        '=', 86,
        '@', 3,
        'g', 75,
        'u', 114,
      );
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(116);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(116);
      END_STATE();
    case 108:
      ACCEPT_TOKEN(sym_identifier);
      ADVANCE_MAP(
        '"', 2,
        '(', 66,
        ')', 71,
        ';', 81,
        '=', 86,
        '@', 3,
        'i', 110,
        'u', 114,
      );
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(116);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(116);
      END_STATE();
    case 109:
      ACCEPT_TOKEN(sym_identifier);
      ADVANCE_MAP(
        '"', 2,
        '(', 66,
        ')', 71,
        ';', 81,
        '=', 86,
        '@', 3,
        'm', 112,
        'u', 114,
      );
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(116);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(116);
      END_STATE();
    case 110:
      ACCEPT_TOKEN(sym_identifier);
      ADVANCE_MAP(
        '"', 2,
        '(', 66,
        ')', 71,
        ';', 81,
        '=', 86,
        '@', 3,
        'n', 107,
        'u', 114,
      );
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(116);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(116);
      END_STATE();
    case 111:
      ACCEPT_TOKEN(sym_identifier);
      ADVANCE_MAP(
        '"', 2,
        '(', 66,
        ')', 71,
        ';', 81,
        '=', 86,
        '@', 3,
        'o', 113,
        'u', 114,
      );
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(116);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(116);
      END_STATE();
    case 112:
      ACCEPT_TOKEN(sym_identifier);
      ADVANCE_MAP(
        '"', 2,
        '(', 66,
        ')', 71,
        ';', 81,
        '=', 86,
        '@', 3,
        'p', 111,
        'u', 114,
      );
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(116);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(116);
      END_STATE();
    case 113:
      ACCEPT_TOKEN(sym_identifier);
      ADVANCE_MAP(
        '"', 2,
        '(', 66,
        ')', 71,
        ';', 81,
        '=', 86,
        '@', 3,
        'r', 115,
        'u', 114,
      );
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(116);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(116);
      END_STATE();
    case 114:
      ACCEPT_TOKEN(sym_identifier);
      ADVANCE_MAP(
        '"', 2,
        '(', 66,
        ')', 71,
        ';', 81,
        '=', 86,
        '@', 3,
        's', 108,
        'u', 114,
      );
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(116);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(116);
      END_STATE();
    case 115:
      ACCEPT_TOKEN(sym_identifier);
      ADVANCE_MAP(
        '"', 2,
        '(', 66,
        ')', 71,
        ';', 81,
        '=', 86,
        '@', 3,
        't', 61,
        'u', 114,
      );
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(116);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(116);
      END_STATE();
    case 116:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == '"') ADVANCE(2);
      if (lookahead == '(') ADVANCE(66);
      if (lookahead == ')') ADVANCE(71);
      if (lookahead == ';') ADVANCE(81);
      if (lookahead == '=') ADVANCE(86);
      if (lookahead == '@') ADVANCE(3);
      if (lookahead == 'u') ADVANCE(114);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(116);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(116);
      END_STATE();
    case 117:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'g') ADVANCE(77);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(126);
      END_STATE();
    case 118:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'g') ADVANCE(76);
      if (lookahead == 'u') ADVANCE(124);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(125);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(125);
      END_STATE();
    case 119:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'i') ADVANCE(121);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(126);
      END_STATE();
    case 120:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'i') ADVANCE(122);
      if (lookahead == 'u') ADVANCE(124);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(125);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(125);
      END_STATE();
    case 121:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'n') ADVANCE(117);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(126);
      END_STATE();
    case 122:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'n') ADVANCE(118);
      if (lookahead == 'u') ADVANCE(124);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(125);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(125);
      END_STATE();
    case 123:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 's') ADVANCE(119);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(126);
      END_STATE();
    case 124:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 's') ADVANCE(120);
      if (lookahead == 'u') ADVANCE(124);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(125);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(125);
      END_STATE();
    case 125:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'u') ADVANCE(124);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(125);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(125);
      END_STATE();
    case 126:
      ACCEPT_TOKEN(sym_identifier);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(126);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexerMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 56},
  [2] = {.lex_state = 56},
  [3] = {.lex_state = 56},
  [4] = {.lex_state = 56},
  [5] = {.lex_state = 56},
  [6] = {.lex_state = 42},
  [7] = {.lex_state = 42},
  [8] = {.lex_state = 43},
  [9] = {.lex_state = 0},
  [10] = {.lex_state = 33},
  [11] = {.lex_state = 44},
  [12] = {.lex_state = 21},
  [13] = {.lex_state = 44},
  [14] = {.lex_state = 34},
  [15] = {.lex_state = 44},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [anon_sym_ATimport] = ACTIONS(1),
    [anon_sym_LPAREN] = ACTIONS(1),
    [anon_sym_RPAREN] = ACTIONS(1),
    [anon_sym_using] = ACTIONS(1),
    [anon_sym_SEMI] = ACTIONS(1),
    [anon_sym_EQ] = ACTIONS(1),
    [sym_string_literal] = ACTIONS(1),
    [sym_identifier] = ACTIONS(1),
  },
  [STATE(1)] = {
    [sym_source_file] = STATE(9),
    [sym__imports] = STATE(2),
    [sym_global_import] = STATE(2),
    [sym_alias_import] = STATE(2),
    [aux_sym_source_file_repeat1] = STATE(2),
    [ts_builtin_sym_end] = ACTIONS(3),
    [anon_sym_using] = ACTIONS(5),
    [sym_identifier] = ACTIONS(7),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 4,
    ACTIONS(5), 1,
      anon_sym_using,
    ACTIONS(7), 1,
      sym_identifier,
    ACTIONS(9), 1,
      ts_builtin_sym_end,
    STATE(3), 4,
      sym__imports,
      sym_global_import,
      sym_alias_import,
      aux_sym_source_file_repeat1,
  [16] = 4,
    ACTIONS(11), 1,
      ts_builtin_sym_end,
    ACTIONS(13), 1,
      anon_sym_using,
    ACTIONS(16), 1,
      sym_identifier,
    STATE(3), 4,
      sym__imports,
      sym_global_import,
      sym_alias_import,
      aux_sym_source_file_repeat1,
  [32] = 2,
    ACTIONS(19), 1,
      ts_builtin_sym_end,
    ACTIONS(21), 2,
      anon_sym_using,
      sym_identifier,
  [40] = 2,
    ACTIONS(23), 1,
      ts_builtin_sym_end,
    ACTIONS(25), 2,
      anon_sym_using,
      sym_identifier,
  [48] = 2,
    ACTIONS(27), 1,
      anon_sym_ATimport,
    STATE(11), 1,
      sym__generic_import,
  [55] = 2,
    ACTIONS(27), 1,
      anon_sym_ATimport,
    STATE(13), 1,
      sym__generic_import,
  [62] = 1,
    ACTIONS(29), 1,
      anon_sym_EQ,
  [66] = 1,
    ACTIONS(31), 1,
      ts_builtin_sym_end,
  [70] = 1,
    ACTIONS(33), 1,
      anon_sym_LPAREN,
  [74] = 1,
    ACTIONS(35), 1,
      anon_sym_SEMI,
  [78] = 1,
    ACTIONS(37), 1,
      sym_string_literal,
  [82] = 1,
    ACTIONS(39), 1,
      anon_sym_SEMI,
  [86] = 1,
    ACTIONS(41), 1,
      anon_sym_RPAREN,
  [90] = 1,
    ACTIONS(43), 1,
      anon_sym_SEMI,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(2)] = 0,
  [SMALL_STATE(3)] = 16,
  [SMALL_STATE(4)] = 32,
  [SMALL_STATE(5)] = 40,
  [SMALL_STATE(6)] = 48,
  [SMALL_STATE(7)] = 55,
  [SMALL_STATE(8)] = 62,
  [SMALL_STATE(9)] = 66,
  [SMALL_STATE(10)] = 70,
  [SMALL_STATE(11)] = 74,
  [SMALL_STATE(12)] = 78,
  [SMALL_STATE(13)] = 82,
  [SMALL_STATE(14)] = 86,
  [SMALL_STATE(15)] = 90,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 0, 0, 0),
  [5] = {.entry = {.count = 1, .reusable = false}}, SHIFT(6),
  [7] = {.entry = {.count = 1, .reusable = false}}, SHIFT(8),
  [9] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1, 0, 0),
  [11] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0),
  [13] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(6),
  [16] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(8),
  [19] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_global_import, 3, 0, 1),
  [21] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_global_import, 3, 0, 1),
  [23] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_alias_import, 4, 0, 2),
  [25] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_alias_import, 4, 0, 2),
  [27] = {.entry = {.count = 1, .reusable = true}}, SHIFT(10),
  [29] = {.entry = {.count = 1, .reusable = true}}, SHIFT(7),
  [31] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [33] = {.entry = {.count = 1, .reusable = true}}, SHIFT(12),
  [35] = {.entry = {.count = 1, .reusable = true}}, SHIFT(4),
  [37] = {.entry = {.count = 1, .reusable = true}}, SHIFT(14),
  [39] = {.entry = {.count = 1, .reusable = true}}, SHIFT(5),
  [41] = {.entry = {.count = 1, .reusable = true}}, SHIFT(15),
  [43] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__generic_import, 4, 0, 3),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_naoslang(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .supertype_count = SUPERTYPE_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .field_names = ts_field_names,
    .field_map_slices = ts_field_map_slices,
    .field_map_entries = ts_field_map_entries,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
    .name = "naoslang",
    .max_reserved_word_set_size = 0,
    .metadata = {
      .major_version = 0,
      .minor_version = 0,
      .patch_version = 0,
    },
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
